run:
  tests: false
linters:
  exclusions:
    paths:
      - "examples/"
  enable-all: true
  disable:
    - wrapcheck
    - varnamelen
    - exhaustruct
    - lll
    - wsl
    - nlreturn
    - tagliatelle
    - funlen
    - cyclop
    - tenv
    - depguard
    - gci
